---
title: "MA Gateway Cities Tool"
format: html
editor: visual
---

# 0.0 Environment Set up
# 0.1 Load Packages and Set Global Options
```{r}
library(tidyverse)
library(tidycensus)
library(readxl)
library(writexl)
library(ggrepel)
library(gtsummary)
library(gt)
library(stargazer)
library(here)

#Gloabl Options
#Eliminate scientific notation
options(scipen = 999)
#Sets random seed
set.seed(351)

#Census API Key is installed on this machine. Please visit https://api.census.gov/data/key_signup.html
#to acquire a key.
#Install a key to your machine using tidycensus::census_api_key().
census_api_key("d590f657a113f2f78b5a422462ea00745e79111c", install = TRUE)
```

# 0.2 Time Set up
```{r}
#Setting baseline time based on the current date
current_year <- lubridate::year(Sys.Date())
current_month <- lubridate::month(Sys.Date())
current_day <- as.numeric(lubridate::day(Sys.Date()))

#Single year lag
lag_year <- current_year - 1
#Two digit year abbreviation for the current year
current_year_abbr <- as.numeric(str_sub(as.character(current_year), -2))

#Setting the typical ACS 5-year estimates vintage based on typical release schedules.
#Tables typically are released in the first week of December of the current year
acs_lead_year <- if_else((current_month == 12 & current_day > 12), current_year-1, current_year-2)
acs_trail_year <- acs_lead_year - 4

#Structures
acs_vintage <- paste0(acs_trail_year,"-",acs_lead_year)
```

# 1.0 Load Data
# 1.1 DOR
```{r}
dor.pop <- read_xlsx(here())
```

# 1.2 Census
```{r}
#Load ACS variables for easier filtering
vars.acs <- load_variables(acs_lead_year, dataset = c("acs5"))

#Create a function for recurring {tidycensus} data pulls
acs_call <- function(acs.table_name){
  get_acs(
    table = acs.table_name,
    geography = "county subdivision", #municipalities
    state = "MA", #Only evaluating MA municipalities
    year = acs_lead_year, #Set to the ACS vintage calculated in the chunk above
    survey = "acs5", #Only evaluating 5-year estimates
    moe_level = 95 #Set the margin of error
  ) 
}
```
